### ISSUE TITLE
When i use this it crashes my game

### ISSUE THREAD

**Issue by MicroTheBred** [MeteorDevelopment/meteor-book-dupe-addon#1]
Crashes my game.

![image](https://user-images.githubusercontent.com/79756278/112226561-aae7ae00-8c04-11eb-8e71-045b85a3396c.png)

**Comment by MicroTheBred** [comment]
was using the wrong version of meteor oops

**Comment by jaydevelopsshit** [comment]
I'm using the latest version of meteor and it crashed just like this, the latest meteor update was 15 days ago and this mod got a new release 2 days ago I think? Figure out your compatibility. Anyways, which version should I be using?

**Comment by MicroTheBred** [comment]
> I'm using the latest version of meteor and it crashed just like this, the latest meteor update was 15 days ago and this mod got a new release 2 days ago I think? Figure out your compatibility. Anyways, which version should I be using?

go to the meteor client discord and there should be a beta version channel or something similar, use that version

**Comment by jaydevelopsshit** [comment]
Thank you
