### ISSUE TITLE
[Bug] My Games Crashing whit this plugin on.

### ISSUE THREAD

**Issue by Norletic** [MeteorDevelopment/meteor-book-dupe-addon#2]
**Describe the bug**
So, i installed the addon for the book dupe and followed all necessary things to make it work. So i put it into the mods folder, close it, start minecraft and it crashes. After i remove the addon from the folder, meteor client works just fine (Just whitout the addon).

**To Reproduce**
I followed every step how it should be done. I didn't do any more unnecessary things. (Better said: You probably cant reproduce it willingly)

**Expected behavior**
That the addon would work just fine.

**Screenshots**

**Additional context**
meteor version: 0.4.2, minecraft version 1.16.4

**Comment by MicroTheBred** [comment]
Use the dev version of meteor, it's in the meteor discord.
