### ISSUE TITLE
[Crashes game]

### ISSUE THREAD

**Issue by wijiler** [MeteorDevelopment/meteor-book-dupe-addon#4]
So I have did all steps to use this addon to meteor but whenever I open my game it crashes and singles out this mod as the reason I would love help if I'm being stupid af

**Comment by DarkDareo** [comment]
> So I have did all steps to use this addon to meteor but whenever I open my game it crashes and singles out this mod as the reason I would love help if I'm being stupid af

same thing for me

**Comment by ZombieBrine13092** [comment]
If all three of us are getting the same error, then this is the error we're getting spat at:
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: minegame159/meteorclient/systems/commands/Command
Exit Code: -1

**Comment by seasnail8169** [comment]
All you need to do is use the latest BookDupe Addon and the latest dev build of meteor.
